name: List nuget paths

on: [workflow_dispatch]
jobs:
  displayPaths:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        dotnet: ['5.0.*', '6.0.*']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Configure restore folder
        run: |
          echo "NUGET_PACKAGES=${{ github.workspace }}nuget_cache" >> $GITHUB_ENV
    
      - name: Setup .NET Core ${{ matrix.dotnet }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - name: Display nuget path
        run: dotnet nuget locals all --list
