name: Funet Nuget Packages

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Add xml utils
        run: |
          apt-get install libxml2-utils
      
      - name: Retrieve version
        run: |
          echo "::set-output name=TAG_NAME::$(xmllint --xpath 'string(//Project/PropertyGroup[1]/Version))' a_project/a_project.csproj)"
        id: version

      - name: Show version
        run: echo ${{ steps.version.outputs.TAG_NAME }}
#      - name: Setup .NET Core
#        uses: actions/setup-dotnet@v1
#        with:
#          dotnet-version: '5.0'
#      
#      - name: Build with dotnet
#        run: dotnet build --configuration Release
#      
#      - name: Pack with dotnet
#        run: |
#          dotnet pack b_project/b_project.csproj --output nuget-packages --configuration Release
#          dotnet pack a_project/a_project.csproj --output nuget-packages --configuration Release
#
#      - name: Push with dotnet
#        run: dotnet nuget push nuget-packages/*nupkg --api-key ${{ secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json